apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: wait-for-zookeeper
        image: busybox
        command: ['sh', '-c', 'until nc -z kafkazk 2181; do echo "Waiting for Zookeeper..."; sleep 5; done']
      containers:
      - name: kafka
        image: gaiadock/oilpriceanalyzer:kafka  
        command: ["kafka-manager"] 
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ACTION
          value: "start-kafka"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: kafkazk:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT 
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafkaServer:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        # Imposta i limiti della memoria JVM
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx1G -Xms512M"
        resources:
          requests:
            memory: "1Gi"    # Maggiore richiesta di memoria
            cpu: "500m"      # CPU richiesta aumentata
          limits:
            memory: "2Gi"    # Limite di memoria aumentato
            cpu: "1000m"     # Limite CPU aumentato
