apiVersion: v1
kind: Service
metadata:
  name: kafkazk
  labels:
    app: zookeeper
spec:
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
    name: client
  selector:
    app: zookeeper