name: CI/CD Pipeline for Oil Price Analyzer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pull-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker images from Docker Hub
        env:
          DOCKER_IMAGE_NAME: gaiadock/oilpriceanalyzer
          TAGS: "spark, logstash, kafka, simulationServer"
        run: |
          for TAG in $(echo $TAGS | tr "," "\n"); do
            docker pull $DOCKER_IMAGE_NAME:$TAG
          done

  deploy:
    needs: pull-images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Configure gcloud for kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GKE_CLUSTER_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy to GKE
        env:
          DOCKER_IMAGE_NAME: gaiadock/oilpriceanalyzer
        run: |
          for TAG in spark kafka logstash simulationServer; do
            kubectl set image deployment/oilpriceanalyzer-$TAG \
              $TAG=$DOCKER_IMAGE_NAME:$TAG
          done
