name: CI/CD Pipeline for Oil Price Analyzer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests elasticsearch kafka-python numpy pyspark pyarrow pandas urllib3==1.26.6 
      - name: Run tests
        run: |
          pytest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        env:
          DOCKER_IMAGE_NAME: gaiadock/oilpriceanalyzer
        run: |
          docker build -t $DOCKER_IMAGE_NAME:${{ github.sha }} .
          docker push $DOCKER_IMAGE_NAME:${{ github.sha }}
          docker tag $DOCKER_IMAGE_NAME:${{ github.sha }} $DOCKER_IMAGE_NAME:latest
          docker push $DOCKER_IMAGE_NAME:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Configure gcloud for kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GKE_CLUSTER_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy to GKE
        env:
          DOCKER_IMAGE_NAME: gaiadock/oilpriceanalyzer
        run: |
          kubectl set image deployment/oilpriceanalyzer \
            oilpriceanalyzer=$DOCKER_IMAGE_NAME:${{ github.sha }}

